apiVersion: apps/v1
kind: Deployment
metadata:
  name: lecture-tests-frontend
  labels: {{- include "lt.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels: { app: lecture-tests-frontend }
  template:
    metadata:
      labels: { app: lecture-tests-frontend }
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.images.frontend.repository }}:{{ .Values.images.frontend.tag }}"
          imagePullPolicy: {{ .Values.images.frontend.pullPolicy }}
          ports: [{ containerPort: 80 }]
---
apiVersion: v1
kind: Service
metadata:
  name: lecture-tests-frontend
  labels: {{- include "lt.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  selector: { app: lecture-tests-frontend }
  ports:
    - port: 80
      targetPort: 80
      {{- if eq .Values.frontend.service.type "NodePort" }}
      nodePort: {{ .Values.frontend.service.nodePort }}
      {{- end }}
